spring:
  profiles:
    active: prd

---
#开发环境配置-------------------------
server:
  port: 8081

spring:
  profiles: dev
  application:
    name:  microservicecloud-config-dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kyx?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
#------------------




---
#测试环境配置
server:
  port: 8082

spring:
  profiles: test
  application:
    name:  microservicecloud-config-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kyx?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
#------------------


---
#生产环境
server:
  port: 8083

spring:
  profiles: prd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kyx?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

#------------------
